# prometheus.yml => - targets: ["localhost:3000"]
./prometheus  --web.listen-address="localhost:9093"

# http_request_summary_seconds{route='/'}
# http_request_summary_seconds{method='POST'}
# rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])  => average request for the last 5 minutes
# sum(rate(nodejs_heap_space_size_used_bytes[5m])) by (space) / sum(rate(nodejs_heap_space_size_available_bytes[5m])) by (space)


# histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) 

# "scripts": {
#   "tools": "cd tools && curl -L -O https://github.com/jcbvm/i18n-editor/releases/download/1.0.0/i18n-editor-1.0.0.zip --output i18n-editor-1.0.0.zip && unzip i18n-editor-1.0.0.zip"
# },

# console.log(await sharp(req.file.buffer).resize({ width: 150 }).toBuffer())
